In [1]:
import torch

In [2]:
a = torch.arange(12)

In [3]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# total number of elements
print(a.numel())

# total size
print(a.shape)

12
torch.Size([12])


In [7]:
a.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
a.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
a # no change

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a.reshape(3,-1) # also the same

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
# sampling values from a distribution

torch.randn(3,4) # gaussian

tensor([[ 0.2743,  1.4615, -0.6327,  1.4139],
        [ 0.8585, -0.5386, -0.2809,  0.6172],
        [-0.3785,  0.2065, -0.2190, -0.7406]])

In [15]:
# elementwise operation

x = torch.randn(4)
y = torch.randn(4)

print(x+y, x-y, x*y, x**y)

tensor([-0.9036,  1.6243, -0.0833,  0.6062]) tensor([ 0.7679,  0.1148, -1.1903,  2.4212]) tensor([ 0.0567,  0.6563, -0.3525, -1.3737]) tensor([   nan, 0.8999,    nan, 0.6865])


In [16]:
torch.exp(x) # also element wise

tensor([0.9344, 2.3859, 0.5290, 4.5436])

In [22]:
a = torch.arange(12).reshape(3,4)

b = torch.arange(8).reshape(2,4)

print(a)
print(b)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [23]:
torch.cat((a,b), dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7]])

In [25]:
c = torch.arange(15).reshape(3,-1)

In [26]:
torch.cat((a,c), dim=1)

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
        [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
        [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [29]:
d = torch.arange(3,15).reshape(3,4)
print(d)

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]])


In [31]:
a == d

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
a.sum()

tensor(66)

In [34]:
X = torch.randn(2,3)
Y = torch.randn(3,4)

try:
    print(Y + X)
except Exception as e:
    print(e)

The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1


In [38]:
Y = Y.reshape(-1,3)

In [40]:
X.shape, Y.shape

(torch.Size([2, 3]), torch.Size([4, 3]))

In [41]:
try:
    print(X + Y)
except Exception as e:
    print(e)

The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0


In [53]:
a =  torch.arange(3).reshape((3,1))
b = torch.arange(3).reshape(1,3)


In [54]:
a + b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [55]:
b + a

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [56]:
# indexing and slicing
a[-1], a[1:3]

(tensor([2]),
 tensor([[1],
         [2]]))

In [59]:
a[:] = 34
a

tensor([[34],
        [34],
        [34]])

In [60]:
before = id(a)

a = torch.arange(3).reshape(3,1)

print(id(a), before)

1866069247104 1866157235840


In [61]:
# in place operation
a[:] = torch.arange(3).reshape(3,1)

print(id(a))

# memory location is the same

1866069247104


In [62]:
# converting to numpy tensor and back

A = X.numpy()
B = torch.tensor(A)

print(type(A), type(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [64]:
# getting salar values
a = torch.tensor([3.5])

type(a), type(a.item()), type(float(a))

(torch.Tensor, float, float)

In [71]:
a = torch.randn(2,2,1)
b= torch.randn(1,2,2)

a, b, a + b

(tensor([[[-0.3601],
          [ 1.3599]],
 
         [[ 0.6130],
          [ 0.2160]]]),
 tensor([[[ 1.5275, -0.2951],
          [-1.1270, -2.8975]]]),
 tensor([[[ 1.1674, -0.6552],
          [ 0.2330, -1.5376]],
 
         [[ 2.1404,  0.3178],
          [-0.9110, -2.6815]]]))