In [1]:
import torch

In [2]:
a = torch.arange(12)

In [3]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# total number of elements
print(a.numel())

# total size
print(a.shape)

12
torch.Size([12])


In [7]:
a.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
a.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
a # no change

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a.reshape(3,-1) # also the same

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
# sampling values from a distribution

torch.randn(3,4) # gaussian

tensor([[ 0.2743,  1.4615, -0.6327,  1.4139],
        [ 0.8585, -0.5386, -0.2809,  0.6172],
        [-0.3785,  0.2065, -0.2190, -0.7406]])

In [15]:
# elementwise operation

x = torch.randn(4)
y = torch.randn(4)

print(x+y, x-y, x*y, x**y)

tensor([-0.9036,  1.6243, -0.0833,  0.6062]) tensor([ 0.7679,  0.1148, -1.1903,  2.4212]) tensor([ 0.0567,  0.6563, -0.3525, -1.3737]) tensor([   nan, 0.8999,    nan, 0.6865])


In [16]:
torch.exp(x) # also element wise

tensor([0.9344, 2.3859, 0.5290, 4.5436])