In [1]:
def f(X):
    return 2 * X + 5

In [11]:
def cubic(X):
    return 2 * X ** 3 + 5

In [2]:
import torch

X = torch.normal(0,0.1,(3,4), requires_grad=True)

In [3]:
X

tensor([[ 0.0525,  0.0678,  0.0213,  0.0911],
        [ 0.0982, -0.0013,  0.0942,  0.0509],
        [ 0.0502, -0.1572, -0.0955, -0.0171]], requires_grad=True)

In [4]:
y = f(X)

In [7]:
with torch.no_grad():
    print(y)
    print(y.sum())

tensor([[5.1050, 5.1356, 5.0426, 5.1822],
        [5.1964, 4.9974, 5.1885, 5.1018],
        [5.1005, 4.6855, 4.8090, 4.9658]], grad_fn=<AddBackward0>)
tensor(60.5103)


In [8]:
y.sum().backward()

In [10]:
X.grad, X.grad.shape, X.shape

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

In [15]:
X.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
y = cubic(X)

In [17]:
print(y.detach())

tensor([[5.0003, 5.0006, 5.0000, 5.0015],
        [5.0019, 5.0000, 5.0017, 5.0003],
        [5.0003, 4.9922, 4.9983, 5.0000]])


In [18]:
y.sum().backward()

In [19]:
X.grad, X.grad.shape

(tensor([[1.6535e-02, 2.7590e-02, 2.7244e-03, 4.9806e-02],
         [5.7888e-02, 9.8641e-06, 5.3284e-02, 1.5554e-02],
         [1.5139e-02, 1.4836e-01, 5.4744e-02, 1.7564e-03]]),
 torch.Size([3, 4]))