In [1]:
import torch

In [2]:
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [3]:
input_size = 5
output_size = 2

In [4]:
batch_size = 30
data_size = 100

In [5]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [6]:
torch.randn(10,2)

tensor([[ 0.0696, -0.5384],
        [-2.5938, -1.8000],
        [-0.5629, -1.9857],
        [ 1.7274, -0.3996],
        [ 0.6649, -0.1375],
        [ 0.6514,  0.3945],
        [-0.5390,  0.1210],
        [-0.4893,  0.9386],
        [ 1.3947, -0.9564],
        [ 0.1847,  0.2788]])

In [7]:
class LinearDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        
    def __getitem__(self,index):
        return self.data[index]
    
    def __len__(self):
        return self.len

rand_loader = DataLoader(dataset=LinearDataset(input_size, data_size), batch_size=batch_size, shuffle=True)
    

In [8]:
print(len(rand_loader))

4


In [9]:
torch.randn(input_size, data_size)[0].shape

torch.Size([100])

In [10]:
for x in rand_loader:
    print(x[0])

tensor([-1.9513,  2.8057,  0.1388, -1.8021,  2.1974])
tensor([ 0.3901, -0.6468, -0.4517,  0.3695, -0.2744])
tensor([-0.5730, -0.0498, -0.5794, -0.0084, -0.2050])
tensor([-1.2460, -0.3374, -0.0495, -0.0591,  0.7833])


In [11]:
class Model(nn.Module):
    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)
    
    def forward(self, input):
        output = self.fc(input)
        print("Model: input size: ", input.size())
        print("Model: output size: ", output.size())
        return output

In [13]:
model = Model(input_size, output_size)

In [14]:
if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
    # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
    model = nn.DataParallel(model)

model.to(device)

Let's use 3 GPUs!


DataParallel(
  (module): Model(
    (fc): Linear(in_features=5, out_features=2, bias=True)
  )
)

In [16]:
for data in rand_loader:
    input = data.to(device)
    output = model(input)
    print("Outside: input size", input.size(),
          "output_size", output.size())

Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Model: input size:  torch.Size([10, 5])
Model: output size:  torch.Size([10, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
Model: input size:  torch.Size([4, 5])
Model: output si