In [1]:
import torch

Proving that X * W_xh + H * W_hh == (X + H) * (W_xh + W_hh)

In [2]:
X, W_xh = torch.normal(0,1,(3,1)), torch.normal(0,1,(1,4))
H, W_hh = torch.normal(0,1,(3,4)), torch.normal(0,1,(4,4))

X, H

(tensor([[-0.8738],
         [ 0.3923],
         [ 2.0292]]),
 tensor([[-0.5989, -1.9705,  0.8816, -0.8856],
         [ 1.2952, -2.7224, -2.3835,  0.7258],
         [ 0.0269,  0.3169,  0.5944,  0.5722]]))

In [3]:
torch.matmul(X,W_xh) + torch.matmul(H, W_hh)

tensor([[-0.3132, -0.2237,  5.1734, -1.3800],
        [-3.2508,  0.2698,  8.2052,  4.2742],
        [ 0.4406,  2.3889, -1.1913,  0.1857]])

In [4]:
torch.matmul(torch.cat((X,H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[-0.3132, -0.2237,  5.1734, -1.3800],
        [-3.2508,  0.2698,  8.2052,  4.2742],
        [ 0.4406,  2.3889, -1.1913,  0.1857]])

### Exercises

1. If we use an RNN to predict the next character in a text sequence, what is the required dimension for any output?
  dimension equal to text sequence.
    
2. Why can RNNs express the conditional probability of a token at some time step based on all
the previous tokens in the text sequence?
    I wonder why. I dont think I ve understood language probability too well.
    
3. What happens to the gradient if you backpropagate through a long sequence?
    Reaches 0

4. What are some of the problems associated with the language model described in this section?
    We cant find the correlation between the words